### ISSUE TITLE
Would it be possible to get an RSS feed on the blog

### ISSUE THREAD

**Issue by fconil** [matplotlib/matplotblog#6]
Hi,
Thanks for launching this blog, I would be pleased if you where able to add an RSS feed to get the new articles.
Regards

**Comment by davidevaleriani** [comment]
Hi!
Thanks for the suggestion. The feed is already there ([link](https://matplotlib.org/matplotblog/index.xml)), but I will add a button to the template to make it more evident.

**Comment by fconil** [comment]
Great, I have added it to my news reader.
Thanks !

**Comment by ashwinvis** [comment]
The feed is there but its contents are a bit redundant. It just says "Posts". Are you sure it is working?
https://matplotlib.org/matplotblog/index.xml

**Comment by QuLogic** [comment]
The problem is the `rss.xml` in the aether theme. It's not default, and I don't know what it's trying to do, but it's broken. If you delete it and use the builtin one, then the feed is fine. Since you aren't using submodules and just embed the whole theme, you can just delete that file and it should work.

**Comment by davidevaleriani** [comment]
Thanks @QuLogic, fixed now!
